window.WORDS_IDIOMS = [
  // Everyday phrases (Повседневные)
  {en:"piece of cake",          ru:"проще простого",                 cat:"everyday", ctx_en:"The test was a piece of cake.",                 ctx_ru:"Тест был проще простого."},
  {en:"once in a blue moon",    ru:"очень редко",                    cat:"everyday", ctx_en:"We see each other once in a blue moon.",         ctx_ru:"Мы видимся очень редко."},
  {en:"break a leg",            ru:"ни пуха ни пера",                cat:"everyday", ctx_en:"Break a leg at the audition!",                   ctx_ru:"Ни пуха ни пера на прослушивании!"},
  {en:"raining cats and dogs",  ru:"льёт как из ведра",              cat:"everyday", ctx_en:"Take an umbrella, it's raining cats and dogs.",  ctx_ru:"Возьми зонт, льёт как из ведра."},
  {en:"by heart",               ru:"наизусть",                       cat:"everyday", ctx_en:"I know the song by heart.",                      ctx_ru:"Я знаю песню наизусть."},
  {en:"on the way",             ru:"по дороге, в пути",              cat:"everyday", ctx_en:"I'll buy bread on the way home.",                ctx_ru:"Я куплю хлеб по дороге домой."},
  {en:"by the way",             ru:"кстати",                         cat:"everyday", ctx_en:"By the way, where is John?",                     ctx_ru:"Кстати, где Джон?"},
  {en:"all of a sudden",        ru:"внезапно",                       cat:"everyday", ctx_en:"All of a sudden, the lights went out.",          ctx_ru:"Внезапно свет погас."},
  {en:"so far",                 ru:"пока что",                       cat:"everyday", ctx_en:"So far, everything is fine.",                    ctx_ru:"Пока что всё хорошо."},
  {en:"at first",               ru:"сначала",                        cat:"everyday", ctx_en:"At first, I didn't like the city.",              ctx_ru:"Сначала мне не нравился город."},
  {en:"at last",                ru:"наконец",                        cat:"everyday", ctx_en:"At last, the holidays are here!",                ctx_ru:"Наконец каникулы наступили!"},
  {en:"in the end",             ru:"в конце концов",                 cat:"everyday", ctx_en:"In the end, we agreed on a price.",              ctx_ru:"В конце концов, мы договорились о цене."},
  {en:"in general",             ru:"в общем",                        cat:"everyday", ctx_en:"In general, I like this idea.",                  ctx_ru:"В общем, мне нравится эта идея."},
  {en:"as soon as possible",    ru:"как можно скорее",               cat:"everyday", ctx_en:"Please call me as soon as possible.",            ctx_ru:"Пожалуйста, позвони мне как можно скорее."},
  {en:"out of the blue",        ru:"как гром среди ясного неба",     cat:"everyday", ctx_en:"She called me out of the blue.",                 ctx_ru:"Она позвонила мне как гром среди ясного неба."},
  {en:"more or less",           ru:"более или менее",                cat:"everyday", ctx_en:"The work is more or less done.",                 ctx_ru:"Работа более или менее сделана."},
  {en:"better late than never", ru:"лучше поздно, чем никогда",      cat:"everyday", ctx_en:"You came, and better late than never!",          ctx_ru:"Ты пришёл, и лучше поздно, чем никогда!"},
  {en:"as a matter of fact",    ru:"на самом деле",                  cat:"everyday", ctx_en:"As a matter of fact, I was there too.",          ctx_ru:"На самом деле, я тоже там был."},
  {en:"to make a long story short", ru:"короче говоря",              cat:"everyday", ctx_en:"To make a long story short, we missed the bus.", ctx_ru:"Короче говоря, мы опоздали на автобус."},
  {en:"first of all",           ru:"прежде всего",                   cat:"everyday", ctx_en:"First of all, let's introduce ourselves.",       ctx_ru:"Прежде всего, давайте представимся."},

  // Feelings (Чувства и эмоции)
  {en:"feel blue",              ru:"грустить",                       cat:"feelings", ctx_en:"She feels blue on rainy days.",                  ctx_ru:"Она грустит в дождливые дни."},
  {en:"on cloud nine",          ru:"на седьмом небе от счастья",     cat:"feelings", ctx_en:"He was on cloud nine after the wedding.",        ctx_ru:"Он был на седьмом небе после свадьбы."},
  {en:"drive someone crazy",    ru:"сводить с ума",                  cat:"feelings", ctx_en:"This noise is driving me crazy.",                ctx_ru:"Этот шум сводит меня с ума."},
  {en:"lose one's temper",      ru:"выйти из себя",                  cat:"feelings", ctx_en:"Don't lose your temper with the kids.",          ctx_ru:"Не выходи из себя с детьми."},
  {en:"fall in love",           ru:"влюбиться",                      cat:"feelings", ctx_en:"They fell in love at first sight.",              ctx_ru:"Они влюбились с первого взгляда."},
  {en:"get on someone's nerves",ru:"действовать на нервы",           cat:"feelings", ctx_en:"His jokes get on my nerves.",                    ctx_ru:"Его шутки действуют мне на нервы."},
  {en:"over the moon",          ru:"безумно счастлив",               cat:"feelings", ctx_en:"She was over the moon about the news.",          ctx_ru:"Она была безумно счастлива от новостей."},
  {en:"butterflies in stomach", ru:"мурашки в животе, волнение",     cat:"feelings", ctx_en:"I had butterflies in my stomach before the exam.", ctx_ru:"У меня были мурашки в животе перед экзаменом."},
  {en:"break someone's heart",  ru:"разбить сердце",                 cat:"feelings", ctx_en:"His words broke her heart.",                     ctx_ru:"Его слова разбили ей сердце."},
  {en:"mixed feelings",         ru:"смешанные чувства",              cat:"feelings", ctx_en:"I have mixed feelings about moving.",            ctx_ru:"У меня смешанные чувства по поводу переезда."},
  {en:"cheer up",               ru:"подбодрить, не унывать",         cat:"feelings", ctx_en:"Cheer up, things will get better!",              ctx_ru:"Не унывай, всё наладится!"},
  {en:"calm down",              ru:"успокоиться",                    cat:"feelings", ctx_en:"Please calm down and explain.",                  ctx_ru:"Пожалуйста, успокойся и объясни."},
  {en:"let someone down",       ru:"подвести, разочаровать",         cat:"feelings", ctx_en:"I promise I won't let you down.",                ctx_ru:"Обещаю, я тебя не подведу."},
  {en:"fed up with",            ru:"сыт по горло",                   cat:"feelings", ctx_en:"I'm fed up with this weather.",                  ctx_ru:"Я сыт по горло этой погодой."},
  {en:"in a good mood",         ru:"в хорошем настроении",           cat:"feelings", ctx_en:"She is always in a good mood on Fridays.",       ctx_ru:"По пятницам она всегда в хорошем настроении."},
  {en:"in a bad mood",          ru:"в плохом настроении",            cat:"feelings", ctx_en:"He's been in a bad mood all day.",               ctx_ru:"Он весь день в плохом настроении."},
  {en:"heart of gold",          ru:"золотое сердце",                 cat:"feelings", ctx_en:"My grandmother has a heart of gold.",            ctx_ru:"У моей бабушки золотое сердце."},
  {en:"a pain in the neck",     ru:"заноза, надоедливая проблема",   cat:"feelings", ctx_en:"The new software is a pain in the neck.",        ctx_ru:"Новая программа — настоящая заноза."},
  {en:"keep one's cool",        ru:"сохранять спокойствие",          cat:"feelings", ctx_en:"She kept her cool during the argument.",         ctx_ru:"Она сохраняла спокойствие во время спора."},
  {en:"have a soft spot for",   ru:"питать слабость к",              cat:"feelings", ctx_en:"I have a soft spot for stray cats.",             ctx_ru:"Я питаю слабость к бездомным кошкам."},

  // Time and money (Время и деньги)
  {en:"time flies",             ru:"время летит",                    cat:"time", ctx_en:"Time flies when you're having fun.",                 ctx_ru:"Время летит, когда тебе весело."},
  {en:"kill time",              ru:"убивать время",                  cat:"time", ctx_en:"We played cards to kill time.",                      ctx_ru:"Мы играли в карты, чтобы убить время."},
  {en:"waste time",             ru:"тратить время впустую",          cat:"time", ctx_en:"Don't waste time on small details.",                 ctx_ru:"Не трать время впустую на мелочи."},
  {en:"in no time",             ru:"в одно мгновение",               cat:"time", ctx_en:"He fixed the bike in no time.",                      ctx_ru:"Он починил велосипед в одно мгновение."},
  {en:"ahead of time",          ru:"заранее, с опережением",         cat:"time", ctx_en:"We finished the project ahead of time.",             ctx_ru:"Мы закончили проект с опережением."},
  {en:"on time",                ru:"вовремя",                        cat:"time", ctx_en:"The train arrived on time.",                         ctx_ru:"Поезд прибыл вовремя."},
  {en:"in time",                ru:"вовремя, успеть",                cat:"time", ctx_en:"I got home in time for dinner.",                     ctx_ru:"Я вернулся домой как раз к ужину."},
  {en:"from time to time",      ru:"время от времени",               cat:"time", ctx_en:"From time to time, we visit the museum.",            ctx_ru:"Время от времени мы посещаем музей."},
  {en:"all the time",           ru:"всё время",                      cat:"time", ctx_en:"He talks about football all the time.",              ctx_ru:"Он всё время говорит о футболе."},
  {en:"running out of time",    ru:"времени в обрез",                cat:"time", ctx_en:"Hurry up, we're running out of time!",               ctx_ru:"Поторопись, у нас времени в обрез!"},
  {en:"time is money",          ru:"время — деньги",                 cat:"time", ctx_en:"In business, time is money.",                        ctx_ru:"В бизнесе время — деньги."},
  {en:"make money",             ru:"зарабатывать деньги",            cat:"time", ctx_en:"He makes good money as a programmer.",               ctx_ru:"Он хорошо зарабатывает как программист."},
  {en:"save money",             ru:"копить деньги",                  cat:"time", ctx_en:"We save money for a holiday every year.",            ctx_ru:"Мы копим деньги на отпуск каждый год."},
  {en:"spend money",            ru:"тратить деньги",                 cat:"time", ctx_en:"She spends money on books.",                         ctx_ru:"Она тратит деньги на книги."},
  {en:"cost a fortune",         ru:"стоить целое состояние",         cat:"time", ctx_en:"That car costs a fortune.",                          ctx_ru:"Эта машина стоит целое состояние."},
  {en:"break the bank",         ru:"разорить, обойтись слишком дорого", cat:"time", ctx_en:"A nice dinner won't break the bank.",             ctx_ru:"Хороший ужин нас не разорит."},
  {en:"tight on money",         ru:"в стеснённых обстоятельствах",   cat:"time", ctx_en:"We're a bit tight on money this month.",             ctx_ru:"В этом месяце у нас туго с деньгами."},
  {en:"rolling in money",       ru:"купаться в деньгах",             cat:"time", ctx_en:"After the deal, he was rolling in money.",           ctx_ru:"После сделки он купался в деньгах."},
  {en:"a rip-off",              ru:"обдираловка",                    cat:"time", ctx_en:"Twenty dollars for coffee? What a rip-off!",         ctx_ru:"Двадцать долларов за кофе? Вот обдираловка!"},
  {en:"pay attention",          ru:"обращать внимание",              cat:"time", ctx_en:"Please pay attention to the speaker.",               ctx_ru:"Пожалуйста, обращайте внимание на докладчика."},

  // Effort, work, study (Учёба и усилия)
  {en:"give it a try",          ru:"попробовать",                    cat:"effort", ctx_en:"Just give it a try, it's not difficult.",          ctx_ru:"Просто попробуй, это не сложно."},
  {en:"do one's best",          ru:"стараться изо всех сил",         cat:"effort", ctx_en:"I will do my best to help you.",                   ctx_ru:"Я сделаю всё возможное, чтобы помочь тебе."},
  {en:"give up",                ru:"сдаться",                        cat:"effort", ctx_en:"Don't give up on your dreams.",                    ctx_ru:"Не отказывайся от своей мечты."},
  {en:"keep going",             ru:"продолжать, не останавливаться", cat:"effort", ctx_en:"It's hard, but keep going.",                       ctx_ru:"Это трудно, но продолжай."},
  {en:"work hard",              ru:"усердно работать",               cat:"effort", ctx_en:"You have to work hard to succeed.",                ctx_ru:"Чтобы преуспеть, нужно усердно работать."},
  {en:"take a break",           ru:"сделать перерыв",                cat:"effort", ctx_en:"Let's take a break for ten minutes.",              ctx_ru:"Давайте сделаем перерыв на десять минут."},
  {en:"get the hang of",        ru:"научиться, освоить",             cat:"effort", ctx_en:"I'm getting the hang of the new app.",             ctx_ru:"Я начинаю осваивать новое приложение."},
  {en:"make progress",          ru:"делать успехи",                  cat:"effort", ctx_en:"She is making real progress in English.",          ctx_ru:"Она делает реальные успехи в английском."},
  {en:"step by step",           ru:"шаг за шагом",                   cat:"effort", ctx_en:"Learn the rules step by step.",                    ctx_ru:"Изучай правила шаг за шагом."},
  {en:"hit the books",          ru:"сесть за учёбу",                 cat:"effort", ctx_en:"I need to hit the books before the exam.",         ctx_ru:"Мне нужно сесть за учёбу перед экзаменом."},
  {en:"learn by heart",         ru:"выучить наизусть",               cat:"effort", ctx_en:"We had to learn the poem by heart.",               ctx_ru:"Нам пришлось выучить стихотворение наизусть."},
  {en:"catch up with",          ru:"догонять",                       cat:"effort", ctx_en:"I need to catch up with the class.",               ctx_ru:"Мне нужно догнать класс."},
  {en:"fall behind",            ru:"отставать",                      cat:"effort", ctx_en:"He fell behind in maths.",                         ctx_ru:"Он отстал по математике."},
  {en:"get ahead",              ru:"преуспевать, продвигаться",      cat:"effort", ctx_en:"You must work hard to get ahead.",                 ctx_ru:"Чтобы преуспеть, нужно усердно работать."},
  {en:"burn the midnight oil",  ru:"работать до поздней ночи",       cat:"effort", ctx_en:"She burned the midnight oil before finals.",       ctx_ru:"Она работала допоздна перед экзаменами."},
  {en:"easier said than done",  ru:"легче сказать, чем сделать",     cat:"effort", ctx_en:"Quitting smoking is easier said than done.",       ctx_ru:"Бросить курить легче сказать, чем сделать."},
  {en:"pull oneself together",  ru:"взять себя в руки",              cat:"effort", ctx_en:"Pull yourself together and finish the report.",    ctx_ru:"Возьми себя в руки и закончи отчёт."},
  {en:"hands-on experience",    ru:"практический опыт",              cat:"effort", ctx_en:"Internships give hands-on experience.",            ctx_ru:"Стажировки дают практический опыт."},
  {en:"learn the ropes",        ru:"осваиваться, узнать тонкости",   cat:"effort", ctx_en:"It takes time to learn the ropes at a new job.",   ctx_ru:"Чтобы освоиться на новой работе, нужно время."},
  {en:"go the extra mile",      ru:"делать больше, чем нужно",       cat:"effort", ctx_en:"Good teachers go the extra mile for students.",    ctx_ru:"Хорошие учителя делают для учеников больше, чем нужно."},
];
