window.GRAMMAR = [
  // ═══════════════════ A1 ═══════════════════
  {
    id: 'to_be',
    level: 'A1',
    title: 'To be (am / is / are)',
    summary: 'Глагол «быть» в настоящем времени',
    rule: 'To be — глагол «быть». Формы зависят от подлежащего: I am, you/we/they are, he/she/it is. Сокращения: I\'m, you\'re, he\'s, she\'s, it\'s, we\'re, they\'re. Отрицание — добавляем not: isn\'t, aren\'t. В вопросе глагол ставится перед подлежащим: Are you ready?',
    table: [
      { form: 'I + am (I\'m)',                              ex: 'I am a student.' },
      { form: 'You / We / They + are (you\'re, we\'re)',    ex: 'They are at home.' },
      { form: 'He / She / It + is (he\'s, she\'s, it\'s)',  ex: 'She is happy.' },
      { form: 'Negative: am/is/are + not (isn\'t, aren\'t)', ex: "He isn't here." },
      { form: 'Question: Am/Is/Are + subject?',             ex: 'Are you tired?' },
    ],
    examples: [
      { en: 'I am from Russia.',         ru: 'Я из России.' },
      { en: 'She is twenty years old.',  ru: 'Ей двадцать лет.' },
      { en: "They aren't ready.",        ru: 'Они не готовы.' },
      { en: 'Is your sister at home?',   ru: 'Твоя сестра дома?' },
    ],
    exercises: [
      { sentence: 'I ___ a teacher.',                    hint: 'I',                    answers: ['am', "'m"],                              translation: 'Я учитель.' },
      { sentence: 'She ___ very tired today.',           hint: 'she',                  answers: ['is'],                                    translation: 'Она сегодня очень устала.' },
      { sentence: 'We ___ from Spain.',                  hint: 'we',                   answers: ['are'],                                   translation: 'Мы из Испании.' },
      { sentence: 'He ___ at home now.',                 hint: 'отрицание: is not',    answers: ["isn't", 'is not'],                       translation: 'Его сейчас нет дома.' },
      { sentence: '___ you ready for school?',           hint: 'вопрос',               answers: ['are'],                                   translation: 'Ты готов в школу?' },
      { sentence: 'They ___ my best friends.',           hint: 'they',                 answers: ['are'],                                   translation: 'Они мои лучшие друзья.' },
    ],
  },

  {
    id: 'present_simple',
    level: 'A1',
    title: 'Present Simple',
    summary: 'Регулярные действия, факты и привычки',
    rule: 'Present Simple используется для регулярных действий, привычек, общих фактов и расписаний. Часто употребляется с наречиями частоты: always, usually, often, sometimes, never; а также every day / week / year.',
    table: [
      { form: 'I / You / We / They + verb',           ex: 'I work in an office.' },
      { form: 'He / She / It + verb-s',                ex: 'She works in an office.' },
      { form: 'do / does + not + verb (отрицание)',    ex: "He doesn't work here." },
      { form: 'Do / Does + subject + verb? (вопрос)',  ex: 'Do you work here?' },
    ],
    examples: [
      { en: 'I get up at seven every day.',     ru: 'Я встаю в семь каждый день.' },
      { en: 'She speaks three languages.',      ru: 'Она говорит на трёх языках.' },
      { en: "We don't live in London.",         ru: 'Мы не живём в Лондоне.' },
      { en: 'Does he play tennis on Sundays?',  ru: 'Он играет в теннис по воскресеньям?' },
    ],
    exercises: [
      { sentence: 'She ___ to school every day.',     hint: 'go',        answers: ['goes'],                              translation: 'Она ходит в школу каждый день.' },
      { sentence: 'I usually ___ tea in the morning.', hint: 'drink',     answers: ['drink'],                             translation: 'Обычно я пью чай по утрам.' },
      { sentence: 'He ___ work on Sundays.',           hint: 'not work',  answers: ["doesn't work", 'does not work'],     translation: 'Он не работает по воскресеньям.' },
      { sentence: '___ you speak French?',             hint: 'do / does', answers: ['do'],                                translation: 'Ты говоришь по-французски?' },
      { sentence: 'My brother ___ pizza.',             hint: 'love',      answers: ['loves'],                             translation: 'Мой брат любит пиццу.' },
      { sentence: 'They ___ in this city.',            hint: 'not live',  answers: ["don't live", 'do not live'],         translation: 'Они не живут в этом городе.' },
    ],
  },

  {
    id: 'plurals',
    level: 'A1',
    title: 'Множественное число',
    summary: 'Plural nouns: правильные и неправильные формы',
    rule: 'Большинство существительных образуют множественное число добавлением -s (book → books). После -s, -x, -ch, -sh, -o добавляется -es (bus → buses, box → boxes, watch → watches, dish → dishes, potato → potatoes). Согласный + y → -ies (city → cities). Слова на -f / -fe → -ves (leaf → leaves, knife → knives). Неправильные формы: man → men, woman → women, child → children, foot → feet, tooth → teeth, mouse → mice, person → people.',
    table: [
      { form: 'Большинство: + s',                  ex: 'book → books' },
      { form: 'После s, x, ch, sh, o: + es',       ex: 'bus → buses, box → boxes' },
      { form: 'Согласный + y → ies',               ex: 'city → cities, baby → babies' },
      { form: 'f / fe → ves',                      ex: 'wife → wives, knife → knives' },
      { form: 'Неправильные',                      ex: 'man → men, child → children, foot → feet' },
    ],
    examples: [
      { en: 'I have two brothers and three sisters.',   ru: 'У меня два брата и три сестры.' },
      { en: 'These boxes are very heavy.',              ru: 'Эти коробки очень тяжёлые.' },
      { en: 'She has three children.',                  ru: 'У неё трое детей.' },
      { en: 'All the babies are sleeping.',             ru: 'Все малыши спят.' },
    ],
    exercises: [
      { sentence: 'one box → two ___',     hint: 'box',    answers: ['boxes'],    translation: 'одна коробка → две коробки' },
      { sentence: 'one city → many ___',   hint: 'city',   answers: ['cities'],   translation: 'один город → много городов' },
      { sentence: 'one child → three ___', hint: 'child',  answers: ['children'], translation: 'один ребёнок → трое детей' },
      { sentence: 'one knife → two ___',   hint: 'knife',  answers: ['knives'],   translation: 'один нож → два ножа' },
      { sentence: 'one tooth → many ___',  hint: 'tooth',  answers: ['teeth'],    translation: 'один зуб → много зубов' },
      { sentence: 'one mouse → many ___',  hint: 'mouse',  answers: ['mice'],     translation: 'одна мышь → много мышей' },
    ],
  },

  {
    id: 'articles',
    level: 'A1',
    title: 'Артикли (a / an / the)',
    summary: 'Неопределённый и определённый артикли',
    rule: 'a / an — неопределённый артикль для исчисляемых существительных в единственном числе. a — перед согласным звуком (a book), an — перед гласным звуком (an apple). The — определённый артикль: для конкретного предмета, для упомянутого ранее, для единственного в своём роде (the sun, the Earth). Без артикля — множественное число в общем смысле (Cats are cute) и большинство имён собственных.',
    table: [
      { form: 'a + согласный звук',           ex: 'a car, a book, a university' },
      { form: 'an + гласный звук',            ex: 'an apple, an hour, an orange' },
      { form: 'the + конкретное / уникальное', ex: 'the sun, the book on the table' },
      { form: '∅ + множественное в общем',    ex: 'Dogs bark. Books are useful.' },
    ],
    examples: [
      { en: 'I have a brother and a sister.',         ru: 'У меня есть брат и сестра.' },
      { en: 'She is reading an interesting book.',    ru: 'Она читает интересную книгу.' },
      { en: 'The sun is hot today.',                  ru: 'Солнце сегодня жаркое.' },
      { en: 'Cats love fish.',                        ru: 'Кошки любят рыбу.' },
    ],
    exercises: [
      { sentence: 'I bought ___ new car.',              hint: 'a / an',  answers: ['a'],   translation: 'Я купил новую машину.' },
      { sentence: 'She has ___ orange in her bag.',     hint: 'a / an',  answers: ['an'],  translation: 'У неё в сумке апельсин.' },
      { sentence: '___ sky is blue today.',             hint: 'the / —', answers: ['the'], translation: 'Небо сегодня голубое.' },
      { sentence: 'Open ___ door, please.',             hint: 'the / —', answers: ['the'], translation: 'Открой дверь, пожалуйста.' },
      { sentence: 'This is ___ easy question.',         hint: 'a / an',  answers: ['an'],  translation: 'Это лёгкий вопрос.' },
      { sentence: '___ Moon goes around the Earth.',    hint: 'the / —', answers: ['the'], translation: 'Луна вращается вокруг Земли.' },
    ],
  },

  {
    id: 'possessives',
    level: 'A1',
    title: 'Притяжательные местоимения',
    summary: 'my, your, his, her, its, our, their',
    rule: 'Притяжательные местоимения ставятся перед существительным. I → my, you → your, he → his, she → her, it → its, we → our, they → their. Для существительных принадлежность выражается через \'s (Anna\'s book) или \' для множественного (the boys\' bikes).',
    table: [
      { form: 'I → my, You → your',                ex: 'my book, your idea' },
      { form: 'He → his, She → her',               ex: 'his car, her name' },
      { form: 'It → its, We → our',                ex: 'its tail, our house' },
      { form: 'They → their',                      ex: 'their dog' },
      { form: "Существительное + 's",              ex: "Anna's book, the cat's tail" },
    ],
    examples: [
      { en: 'This is my book.',           ru: 'Это моя книга.' },
      { en: 'His sister is a nurse.',     ru: 'Его сестра — медсестра.' },
      { en: 'We love our city.',          ru: 'Мы любим наш город.' },
      { en: "Sam's car is red.",          ru: 'Машина Сэма красная.' },
    ],
    exercises: [
      { sentence: 'This is ___ book.',              hint: 'I',     answers: ['my'],    translation: 'Это моя книга.' },
      { sentence: '___ mother is a teacher.',       hint: 'She',   answers: ['her'],   translation: 'Её мама — учительница.' },
      { sentence: 'We love ___ country.',           hint: 'we',    answers: ['our'],   translation: 'Мы любим нашу страну.' },
      { sentence: '___ name is John.',              hint: 'He',    answers: ['his'],   translation: 'Его зовут Джон.' },
      { sentence: 'The dog wags ___ tail.',         hint: 'it',    answers: ['its'],   translation: 'Собака виляет хвостом.' },
      { sentence: '___ children are at school.',    hint: 'They',  answers: ['their'], translation: 'Их дети в школе.' },
    ],
  },

  // ═══════════════════ A2 ═══════════════════
  {
    id: 'present_continuous',
    level: 'A2',
    title: 'Present Continuous',
    summary: 'Действия в момент речи и временные ситуации',
    rule: 'Present Continuous = am / is / are + V-ing. Используется для действий, которые происходят прямо сейчас (right now, at the moment), для временных ситуаций (this week, these days), для запланированных будущих событий (I\'m meeting John tomorrow).',
    table: [
      { form: 'I + am + V-ing',                          ex: 'I am working.' },
      { form: 'He / She / It + is + V-ing',              ex: 'She is reading.' },
      { form: 'You / We / They + are + V-ing',           ex: 'We are studying.' },
      { form: 'Negative: am/is/are + not + V-ing',       ex: "He isn't sleeping." },
      { form: 'Question: Am/Is/Are + subject + V-ing?',  ex: 'Are you working?' },
    ],
    examples: [
      { en: 'I am reading a book right now.',     ru: 'Я сейчас читаю книгу.' },
      { en: 'She is working at home today.',      ru: 'Она сегодня работает дома.' },
      { en: "They aren't watching TV.",           ru: 'Они не смотрят телевизор.' },
      { en: 'What are you doing?',                ru: 'Что ты делаешь?' },
    ],
    exercises: [
      { sentence: 'He ___ a book right now.',           hint: 'read',       answers: ['is reading'],                              translation: 'Он сейчас читает книгу.' },
      { sentence: 'They ___ TV at the moment.',         hint: 'watch',      answers: ['are watching'],                            translation: 'Они в данный момент смотрят телевизор.' },
      { sentence: 'I ___ Spanish this year.',           hint: 'study',      answers: ['am studying', "'m studying"],              translation: 'В этом году я изучаю испанский.' },
      { sentence: 'She ___ at the moment.',             hint: 'not sleep',  answers: ["isn't sleeping", 'is not sleeping'],       translation: 'Она сейчас не спит.' },
      { sentence: 'Are you ___ to music?',              hint: 'listen',     answers: ['listening'],                               translation: 'Ты слушаешь музыку?' },
      { sentence: 'The kids ___ in the garden.',        hint: 'play',       answers: ['are playing'],                             translation: 'Дети играют в саду.' },
    ],
  },

  {
    id: 'past_simple',
    level: 'A2',
    title: 'Past Simple',
    summary: 'Простое прошедшее время',
    rule: 'Past Simple — простое прошедшее. Регулярные глаголы: + ed (work → worked, play → played). Неправильные глаголы — отдельная таблица (go → went, see → saw, have → had, do → did). Отрицание и вопрос — через did / didn\'t + базовая форма: Did you go? He didn\'t go. У глагола be — особые формы: was (I/he/she/it), were (you/we/they).',
    table: [
      { form: 'Regular: V + ed',                            ex: 'work → worked, play → played' },
      { form: 'Irregular',                                  ex: 'go → went, see → saw, have → had' },
      { form: "Negative: didn't + V (база)",                ex: "She didn't come." },
      { form: 'Question: Did + subject + V?',               ex: 'Did you see him?' },
      { form: 'Be: was (I, he, she, it), were (you, we, they)', ex: 'I was tired. They were here.' },
    ],
    examples: [
      { en: 'I worked late yesterday.',          ru: 'Я работал допоздна вчера.' },
      { en: 'She went to Paris last summer.',    ru: 'Она ездила в Париж прошлым летом.' },
      { en: "We didn't see the movie.",          ru: 'Мы не видели этот фильм.' },
      { en: 'Did he call you?',                  ru: 'Он тебе звонил?' },
    ],
    exercises: [
      { sentence: 'I ___ to the cinema yesterday.',    hint: 'go',          answers: ['went'],                                     translation: 'Я вчера ходил в кино.' },
      { sentence: 'She ___ him last week.',            hint: 'see',         answers: ['saw'],                                      translation: 'Она видела его на прошлой неделе.' },
      { sentence: 'We ___ a great time on holiday.',   hint: 'have',        answers: ['had'],                                      translation: 'Мы прекрасно провели время в отпуске.' },
      { sentence: 'They ___ the email.',               hint: 'not receive', answers: ["didn't receive", 'did not receive'],        translation: 'Они не получили письмо.' },
      { sentence: 'He ___ his keys this morning.',     hint: 'lose',        answers: ['lost'],                                     translation: 'Он потерял ключи сегодня утром.' },
      { sentence: '___ you finish the book?',          hint: 'вспомог.',    answers: ['did'],                                      translation: 'Ты дочитал книгу?' },
    ],
  },

  {
    id: 'future',
    level: 'A2',
    title: 'Будущее: going to / will',
    summary: 'Two ways to talk about the future',
    rule: 'going to — для запланированных намерений и прогнозов на основе видимого факта (Look at those clouds! It\'s going to rain). will — для решений в момент речи, обещаний и предсказаний без явных оснований (I think it will be fine. I\'ll help you!). Сокращения: I\'ll, you\'ll, won\'t.',
    table: [
      { form: 'Plans / intention: am/is/are + going to + V',  ex: "I'm going to study tonight." },
      { form: 'Spontaneous decisions / promise: will + V',    ex: "I'll help you!" },
      { form: 'Predictions: оба варианта возможны',           ex: 'It will rain. / It is going to rain.' },
      { form: "Negative: won't / am/is/are not going to",     ex: "She won't come." },
    ],
    examples: [
      { en: "I'm going to visit my grandma tomorrow.",         ru: 'Я собираюсь навестить бабушку завтра.' },
      { en: "It's going to rain — look at the clouds.",        ru: 'Сейчас пойдёт дождь — посмотри на облака.' },
      { en: 'I will help you with your bag.',                  ru: 'Я помогу тебе с сумкой.' },
      { en: "She won't come to the party.",                    ru: 'Она не придёт на вечеринку.' },
    ],
    exercises: [
      { sentence: "Tomorrow I'm ___ visit my parents.",    hint: 'going to',  answers: ['going to'],            translation: 'Завтра я еду к родителям.' },
      { sentence: 'The phone is ringing. I ___ answer it.', hint: 'will',      answers: ['will', "'ll"],         translation: 'Телефон звонит. Я отвечу.' },
      { sentence: "Watch out! You're ___ fall!",            hint: 'going to',  answers: ['going to'],            translation: 'Осторожно! Ты сейчас упадёшь!' },
      { sentence: "Don't worry, I ___ help you.",           hint: 'will',      answers: ['will', "'ll"],         translation: 'Не волнуйся, я помогу.' },
      { sentence: "Look at those clouds. It's ___ rain.",   hint: 'going to',  answers: ['going to'],            translation: 'Посмотри на тучи. Сейчас пойдёт дождь.' },
      { sentence: 'I think she ___ pass the exam.',         hint: 'will',      answers: ['will', "'ll"],         translation: 'Я думаю, она сдаст экзамен.' },
    ],
  },

  {
    id: 'comparatives',
    level: 'A2',
    title: 'Сравнительная и превосходная',
    summary: 'Comparatives & Superlatives',
    rule: 'Короткие прилагательные (1–2 слога): + er / + est (small → smaller → smallest). Окончание -y: y → ier / iest (happy → happier → happiest). Длинные прилагательные: more / most + adj (interesting → more interesting → most interesting). Неправильные: good → better → best, bad → worse → worst, far → further/farther → furthest/farthest.',
    table: [
      { form: 'Короткие: + er / + est',           ex: 'fast → faster → fastest' },
      { form: 'Конечное y: y → ier / iest',       ex: 'happy → happier → happiest' },
      { form: 'Длинные: more / most',             ex: 'beautiful → more beautiful → most beautiful' },
      { form: 'Неправильные',                     ex: 'good → better → best; bad → worse → worst' },
    ],
    examples: [
      { en: 'This book is more interesting than that one.', ru: 'Эта книга интереснее той.' },
      { en: 'Jane is the tallest girl in the class.',       ru: 'Джейн — самая высокая в классе.' },
      { en: 'My new car is better than the old one.',       ru: 'Моя новая машина лучше старой.' },
      { en: 'This is the worst day of my life.',            ru: 'Это худший день в моей жизни.' },
    ],
    exercises: [
      { sentence: 'This pen is ___ than that one.',           hint: 'cheap (сравн.)',      answers: ['cheaper'],          translation: 'Эта ручка дешевле той.' },
      { sentence: 'Football is the ___ sport in many countries.', hint: 'popular (превосх.)', answers: ['most popular'],   translation: 'Футбол — самый популярный спорт во многих странах.' },
      { sentence: 'He is ___ than his brother.',              hint: 'tall (сравн.)',       answers: ['taller'],           translation: 'Он выше своего брата.' },
      { sentence: 'She is the ___ student in the class.',     hint: 'intelligent (превосх.)', answers: ['most intelligent'], translation: 'Она самая умная ученица в классе.' },
      { sentence: "This is the ___ film I've ever seen.",     hint: 'good (превосх.)',     answers: ['best'],             translation: 'Это лучший фильм, который я когда-либо видел.' },
      { sentence: 'That was the ___ joke ever!',              hint: 'bad (превосх.)',      answers: ['worst'],            translation: 'Это была худшая шутка в истории!' },
    ],
  },

  {
    id: 'modals_basic',
    level: 'A2',
    title: 'Модальные: can / could / must',
    summary: 'Способность, разрешение, обязанность',
    rule: 'Модальные глаголы выражают способность, возможность, разрешение или обязанность. После них — голый инфинитив (без to). Не меняются по лицам. can — могу/умею (настоящее). could — мог (прошлая способность) или вежливая просьба. must — должен (сильная обязанность). Отрицание: can\'t (cannot), couldn\'t, mustn\'t.',
    table: [
      { form: 'can: ability / permission',          ex: 'I can swim. Can I sit here?' },
      { form: 'could: past ability / polite',       ex: 'She could swim at four. Could you help me?' },
      { form: 'must: strong obligation',            ex: 'You must wear a seatbelt.' },
      { form: "can't / couldn't / mustn't",          ex: "He can't drive yet." },
    ],
    examples: [
      { en: 'I can speak three languages.',     ru: 'Я говорю на трёх языках.' },
      { en: 'She could read at five.',          ru: 'Она умела читать в пять лет.' },
      { en: 'You must drive carefully.',        ru: 'Ты должен ехать осторожно.' },
      { en: 'Can you help me?',                 ru: 'Можешь мне помочь?' },
    ],
    exercises: [
      { sentence: 'I ___ swim very well.',                  hint: 'способность',     answers: ['can'],                       translation: 'Я хорошо плаваю.' },
      { sentence: 'When I was a child, I ___ ride a horse.', hint: 'прошлая способн.', answers: ['could'],                     translation: 'В детстве я умел ездить верхом.' },
      { sentence: 'You ___ wear a helmet on a motorcycle.', hint: 'обязанность',     answers: ['must'],                      translation: 'На мотоцикле ты обязан быть в шлеме.' },
      { sentence: 'He ___ swim — he never learned.',         hint: 'не умеет',        answers: ["can't", 'cannot'],           translation: 'Он не умеет плавать — никогда не учился.' },
      { sentence: '___ you help me with this?',              hint: 'вежливая просьба', answers: ['could', 'can'],              translation: 'Ты не мог бы мне с этим помочь?' },
      { sentence: 'We ___ leave by 7 pm.',                   hint: 'обязанность',     answers: ['must'],                      translation: 'Мы должны уйти к 7 вечера.' },
    ],
  },

  // ═══════════════════ B1 ═══════════════════
  {
    id: 'present_perfect',
    level: 'B1',
    title: 'Present Perfect',
    summary: 'Связь прошлого с настоящим',
    rule: 'Present Perfect = have / has + V3 (третья форма глагола). Используется: 1) для опыта (Have you ever been to Paris?); 2) для недавнего действия с результатом в настоящем (I have lost my keys); 3) с маркерами времени, которое ещё не закончилось (this week, today, since 2010, for ten years). Маркеры: ever, never, just, already, yet, since, for.',
    table: [
      { form: 'I / You / We / They + have + V3',     ex: 'I have seen this film.' },
      { form: 'He / She / It + has + V3',            ex: 'She has finished.' },
      { form: "Negative: haven't / hasn't",          ex: "I haven't been there." },
      { form: 'Question: Have / Has + subj + V3?',   ex: 'Have you eaten?' },
      { form: 'Markers',                             ex: 'ever, never, just, already, yet, since, for' },
    ],
    examples: [
      { en: 'I have lived here for ten years.',       ru: 'Я живу здесь десять лет.' },
      { en: 'She has just finished her homework.',    ru: 'Она только что доделала уроки.' },
      { en: 'Have you ever been to Italy?',           ru: 'Ты когда-нибудь был в Италии?' },
      { en: "They haven't met him yet.",              ru: 'Они с ним ещё не встречались.' },
    ],
    exercises: [
      { sentence: 'I ___ this film three times.',     hint: 'see',          answers: ['have seen'],                                translation: 'Я видел этот фильм три раза.' },
      { sentence: 'She ___ her keys.',                hint: 'lose',         answers: ['has lost'],                                 translation: 'Она потеряла ключи.' },
      { sentence: 'I have ___ to London twice.',      hint: 'be (V3)',      answers: ['been'],                                     translation: 'Я был в Лондоне дважды.' },
      { sentence: 'They ___ the work yet.',           hint: 'not finish',   answers: ["haven't finished", 'have not finished'],    translation: 'Они ещё не закончили работу.' },
      { sentence: 'He ___ here since 2010.',          hint: 'live',         answers: ['has lived'],                                translation: 'Он живёт здесь с 2010 года.' },
      { sentence: 'Have you ___ breakfast yet?',      hint: 'eat (V3)',     answers: ['eaten', 'had'],                             translation: 'Ты уже позавтракал?' },
    ],
  },

  {
    id: 'past_continuous',
    level: 'B1',
    title: 'Past Continuous',
    summary: 'Длительное действие в прошлом',
    rule: 'Past Continuous = was / were + V-ing. Используется для длительного действия в прошлом, особенно когда оно прерывается другим (When she called, I was sleeping), а также для одновременных действий (While she was cooking, he was reading). Маркеры: when, while, at 5 pm yesterday, all day.',
    table: [
      { form: 'I / He / She / It + was + V-ing',     ex: 'I was reading.' },
      { form: 'You / We / They + were + V-ing',      ex: 'They were playing.' },
      { form: "Negative: wasn't / weren't + V-ing",  ex: "He wasn't listening." },
      { form: 'Question: Was / Were + subj + V-ing?', ex: 'Were you working?' },
    ],
    examples: [
      { en: 'I was reading when she called.',     ru: 'Я читал, когда она позвонила.' },
      { en: 'They were playing in the garden.',   ru: 'Они играли в саду.' },
      { en: 'What were you doing at 8?',          ru: 'Что ты делал в 8?' },
      { en: "He wasn't listening.",               ru: 'Он не слушал.' },
    ],
    exercises: [
      { sentence: 'I ___ TV when the lights went out.',    hint: 'watch',        answers: ['was watching'],                              translation: 'Я смотрел телевизор, когда отключили свет.' },
      { sentence: 'They ___ in the park.',                  hint: 'play',         answers: ['were playing'],                              translation: 'Они играли в парке.' },
      { sentence: 'What were you ___ at 6 pm yesterday?',  hint: 'do (V-ing)',   answers: ['doing'],                                     translation: 'Что ты делал вчера в 6 вечера?' },
      { sentence: 'She ___ when I called.',                hint: 'not sleep',    answers: ["wasn't sleeping", 'was not sleeping'],       translation: 'Она не спала, когда я позвонил.' },
      { sentence: 'We ___ dinner at 8.',                   hint: 'have',         answers: ['were having'],                               translation: 'Мы ужинали в 8.' },
      { sentence: 'He ___ a book all evening.',            hint: 'read',         answers: ['was reading'],                               translation: 'Он читал книгу весь вечер.' },
    ],
  },

  {
    id: 'conditionals_01',
    level: 'B1',
    title: 'Conditionals 0 и 1',
    summary: 'Условные предложения нулевого и первого типа',
    rule: 'Zero Conditional — общие истины и научные факты: If + Present Simple, Present Simple. (If you heat ice, it melts.) First Conditional — реальное условие в будущем: If + Present Simple, will + V. (If it rains, I will stay home.) Порядок частей можно менять: I will go if it stops raining.',
    table: [
      { form: 'Zero: If + V (present), V (present)',    ex: 'If you heat water, it boils.' },
      { form: 'First: If + V (present), will + V',      ex: 'If you study, you will pass.' },
      { form: 'Reverse order',                          ex: "I'll go if it stops raining." },
    ],
    examples: [
      { en: 'If you mix red and blue, you get purple.', ru: 'Если смешать красный и синий, получится фиолетовый.' },
      { en: "If it rains, I'll take an umbrella.",       ru: 'Если будет дождь, я возьму зонт.' },
      { en: "We will be late if we don't hurry.",        ru: 'Мы опоздаем, если не поторопимся.' },
      { en: "If she calls, I'll tell you.",              ru: 'Если она позвонит, я тебе скажу.' },
    ],
    exercises: [
      { sentence: 'If you heat water to 100°C, it ___.',     hint: 'boil — Zero',      answers: ['boils'],                                 translation: 'Если нагреть воду до 100°C, она кипит.' },
      { sentence: 'If it ___ tomorrow, we will stay home.',  hint: 'rain — First',     answers: ['rains'],                                 translation: 'Если завтра пойдёт дождь, мы останемся дома.' },
      { sentence: 'I ___ you if I see her.',                 hint: 'will tell',        answers: ['will tell', "'ll tell"],                 translation: 'Я скажу тебе, если её увижу.' },
      { sentence: 'If she ___ early, she catches the bus.',  hint: 'leave — Zero',     answers: ['leaves'],                                translation: 'Если она выходит рано, успевает на автобус.' },
      { sentence: "If you don't hurry, you ___ the train.",  hint: 'miss — First',     answers: ['will miss', "'ll miss"],                 translation: 'Если не поторопишься, опоздаешь на поезд.' },
      { sentence: 'Plants die if you ___ them.',             hint: 'not water — Zero', answers: ["don't water", 'do not water'],           translation: 'Растения погибают, если их не поливать.' },
    ],
  },

  {
    id: 'used_to',
    level: 'B1',
    title: 'used to',
    summary: 'Привычки и состояния в прошлом',
    rule: 'used to + V — для регулярных действий или состояний в прошлом, которые больше не актуальны (I used to smoke = раньше курил, теперь нет). Только в прошлом времени. Отрицание: didn\'t use to. Вопрос: Did + subject + use to + V? После did глагол use идёт без -d.',
    table: [
      { form: 'Affirmative: used to + V',                  ex: 'I used to live in Moscow.' },
      { form: "Negative: didn't use to + V",                ex: "She didn't use to like coffee." },
      { form: 'Question: Did + subj + use to + V?',         ex: 'Did you use to play tennis?' },
    ],
    examples: [
      { en: 'I used to play football when I was young.', ru: 'Я играл в футбол в молодости.' },
      { en: 'She used to live in Spain.',                ru: 'Она раньше жила в Испании.' },
      { en: "We didn't use to have a car.",              ru: 'У нас раньше не было машины.' },
      { en: 'Did you use to read a lot?',                ru: 'Ты раньше много читал?' },
    ],
    exercises: [
      { sentence: 'I ___ smoke, but I quit.',                       hint: 'used to',       answers: ['used to'],                       translation: 'Я раньше курил, но бросил.' },
      { sentence: "She didn't ___ to like vegetables.",              hint: 'use',           answers: ['use'],                           translation: 'Раньше она не любила овощи.' },
      { sentence: 'We ___ live in this house.',                     hint: 'used to',       answers: ['used to'],                       translation: 'Раньше мы жили в этом доме.' },
      { sentence: 'Did you ___ to play tennis?',                    hint: 'use',           answers: ['use'],                           translation: 'Ты раньше играл в теннис?' },
      { sentence: 'He ___ to drink coffee, but now he loves it.',   hint: 'not + use',     answers: ["didn't use", 'did not use'],     translation: 'Он раньше не пил кофе, а сейчас обожает.' },
      { sentence: 'They ___ have a dog, but it died last year.',    hint: 'used to',       answers: ['used to'],                       translation: 'У них раньше была собака, но она умерла в прошлом году.' },
    ],
  },

  // ═══════════════════ B2 ═══════════════════
  {
    id: 'past_perfect',
    level: 'B2',
    title: 'Past Perfect',
    summary: 'Действие до другого действия в прошлом',
    rule: 'Past Perfect = had + V3 (третья форма). Используется для действия, завершённого ДО другого действия в прошлом. Часто с маркерами: already, just, by the time, before, after. (When I arrived, the train had already left.)',
    table: [
      { form: 'All persons: had + V3',         ex: 'She had finished the work.' },
      { form: "Negative: hadn't + V3",         ex: "I hadn't seen him before." },
      { form: 'Question: Had + subj + V3?',    ex: 'Had they left by then?' },
      { form: 'Markers',                       ex: 'already, just, by the time, before, after' },
    ],
    examples: [
      { en: 'When I arrived, the train had already left.', ru: 'Когда я приехал, поезд уже ушёл.' },
      { en: 'She had finished her work by 5 pm.',          ru: 'Она закончила работу к 5 вечера.' },
      { en: 'I had never seen such a film before.',        ru: 'Я никогда раньше не видел такого фильма.' },
      { en: 'After he had eaten, he went out.',            ru: 'После того как он поел, он вышел.' },
    ],
    exercises: [
      { sentence: 'When I arrived, they ___ already eaten.',       hint: 'have / has / had', answers: ['had'],     translation: 'Когда я пришёл, они уже поели.' },
      { sentence: 'She had ___ her keys before she left home.',     hint: 'find (V3)',         answers: ['found'],   translation: 'Она нашла ключи до того, как ушла из дома.' },
      { sentence: 'By the time we got there, the film ___ started.', hint: 'have / has / had', answers: ['had'],     translation: 'К нашему приходу фильм уже начался.' },
      { sentence: 'I had never ___ such a beautiful view.',         hint: 'see (V3)',          answers: ['seen'],    translation: 'Я никогда не видел такого красивого вида.' },
      { sentence: 'After they had ___ dinner, they watched a movie.', hint: 'have (V3)',       answers: ['had'],     translation: 'После ужина они посмотрели фильм.' },
      { sentence: 'He had ___ the book by Sunday.',                  hint: 'finish (V3)',       answers: ['finished'], translation: 'К воскресенью он дочитал книгу.' },
    ],
  },

  {
    id: 'conditionals_23',
    level: 'B2',
    title: 'Conditionals 2 и 3',
    summary: 'Нереальные условия (настоящее и прошлое)',
    rule: 'Second Conditional — нереальное настоящее или будущее: If + Past Simple, would + V. (If I had money, I would buy a car.) Third Conditional — нереальное прошлое: If + Past Perfect, would have + V3. (If I had known, I would have come.) В формальном английском «If I were» (а не was) для всех лиц.',
    table: [
      { form: 'Second: If + V (past), would + V',                 ex: 'If I were you, I would go.' },
      { form: 'Third: If + had + V3, would have + V3',            ex: 'If I had studied, I would have passed.' },
      { form: 'Formal: "If I were" (not "If I was")',             ex: 'If he were rich, he would help us.' },
    ],
    examples: [
      { en: 'If I had a million dollars, I would travel the world.',    ru: 'Если бы у меня был миллион, я бы путешествовал.' },
      { en: 'If I were you, I would tell her.',                          ru: 'На твоём месте я бы ей сказал.' },
      { en: 'If she had studied, she would have passed.',                ru: 'Если бы она училась, она бы сдала.' },
      { en: "If we hadn't come, we would have missed the show.",         ru: 'Если бы мы не пришли, мы бы пропустили шоу.' },
    ],
    exercises: [
      { sentence: 'If I ___ a car, I would drive to work.',                hint: 'have — 2nd',          answers: ['had'],               translation: 'Если бы у меня была машина, я бы ездил на работу.' },
      { sentence: 'If I were you, I ___ accept the offer.',                 hint: 'would',                answers: ['would', "'d"],       translation: 'На твоём месте я бы принял предложение.' },
      { sentence: 'If she had ___, she would have passed.',                 hint: 'study (V3) — 3rd',     answers: ['studied'],           translation: 'Если бы она училась, она бы сдала.' },
      { sentence: "If we ___ taken a taxi, we wouldn't have been late.",    hint: 'have — 3rd',           answers: ['had'],               translation: 'Если бы мы поехали на такси, мы бы не опоздали.' },
      { sentence: 'If he ___ rich, he would buy a yacht.',                  hint: 'be — 2nd (формал.)',  answers: ['were', 'was'],       translation: 'Если бы он был богат, он бы купил яхту.' },
      { sentence: 'If I had known, I ___ come earlier.',                    hint: 'would have',           answers: ['would have'],        translation: 'Если бы я знал, я бы пришёл раньше.' },
    ],
  },

  {
    id: 'reported_speech',
    level: 'B2',
    title: 'Reported Speech',
    summary: 'Косвенная речь',
    rule: 'Reported speech — пересказ слов другого. При сдвиге времён: Present → Past, Past → Past Perfect, will → would, can → could, must → had to. Также сдвигаются местоимения и обстоятельства: now → then, today → that day, here → there, this → that, tomorrow → the next day.',
    table: [
      { form: '"I am tired" → He said he was tired',                ex: 'Present → Past' },
      { form: '"I will help" → She said she would help',            ex: 'will → would' },
      { form: '"I have done it" → He said he had done it',          ex: 'Present Perfect → Past Perfect' },
      { form: '"I went home" → He said he had gone home',           ex: 'Past Simple → Past Perfect' },
      { form: 'can → could; must → had to',                          ex: '"I can swim" → He said he could swim' },
    ],
    examples: [
      { en: 'He said, "I am happy." → He said he was happy.',                 ru: 'Он сказал, что счастлив.' },
      { en: 'She said, "I will call you." → She said she would call me.',     ru: 'Она сказала, что позвонит мне.' },
      { en: '"I went to Paris," he said. → He said he had gone to Paris.',    ru: 'Он сказал, что ездил в Париж.' },
      { en: '"I can swim," she said. → She said she could swim.',             ru: 'Она сказала, что умеет плавать.' },
    ],
    exercises: [
      { sentence: "She said, 'I am tired.' → She said she ___ tired.",         hint: 'be → past',         answers: ['was'],     translation: 'Она сказала, что устала.' },
      { sentence: "He said, 'I will come.' → He said he ___ come.",             hint: 'will → ?',          answers: ['would'],   translation: 'Он сказал, что придёт.' },
      { sentence: "Tom said, 'I have finished.' → Tom said he ___ finished.",   hint: 'have / has → ?',    answers: ['had'],     translation: 'Том сказал, что закончил.' },
      { sentence: "She said, 'I can drive.' → She said she ___ drive.",         hint: 'can → ?',           answers: ['could'],   translation: 'Она сказала, что умеет водить.' },
      { sentence: "'I work here,' he said. → He said he ___ there.",            hint: 'work → past',       answers: ['worked'],  translation: 'Он сказал, что работает там.' },
      { sentence: "'I lost the key,' she said. → She said she ___ the key.",    hint: 'lose → past perf.', answers: ['had lost'], translation: 'Она сказала, что потеряла ключ.' },
    ],
  },

  {
    id: 'passive_voice',
    level: 'B2',
    title: 'Passive Voice',
    summary: 'Страдательный залог',
    rule: 'Passive voice = форма be + V3. Подлежащее — объект действия, а не его исполнитель. Меняется только форма be: am/is/are (Present), was/were (Past), have/has been (Present Perfect), will be (Future). Кто совершил действие — указывается через by (если важно): The book was written by Tolstoy.',
    table: [
      { form: 'Present Simple: am/is/are + V3',          ex: 'Letters are written every day.' },
      { form: 'Past Simple: was/were + V3',              ex: 'The cake was eaten.' },
      { form: 'Present Perfect: have/has been + V3',     ex: 'It has been done.' },
      { form: 'Future: will be + V3',                    ex: 'It will be finished tomorrow.' },
      { form: 'by + agent (если важно)',                 ex: 'The book was written by Tolstoy.' },
    ],
    examples: [
      { en: 'The room is cleaned every day.',          ru: 'Комнату убирают каждый день.' },
      { en: 'This book was written by Tolstoy.',       ru: 'Эта книга написана Толстым.' },
      { en: 'The work has been done.',                 ru: 'Работа сделана.' },
      { en: 'The house will be sold next month.',      ru: 'Дом будет продан в следующем месяце.' },
    ],
    exercises: [
      { sentence: 'The cake ___ by Mary yesterday.',     hint: 'bake — Past Passive',          answers: ['was baked'],         translation: 'Торт был испечён Мэри вчера.' },
      { sentence: 'English ___ all over the world.',     hint: 'speak — Pres Simple Passive',  answers: ['is spoken'],         translation: 'На английском говорят по всему миру.' },
      { sentence: 'The letter ___ tomorrow.',            hint: 'send — Future Passive',         answers: ['will be sent'],      translation: 'Письмо отправят завтра.' },
      { sentence: 'These houses ___ in 1990.',           hint: 'build — Past Passive',          answers: ['were built'],        translation: 'Эти дома были построены в 1990 году.' },
      { sentence: 'The car ___ recently.',               hint: 'repair — Pres Perf Passive',    answers: ['has been repaired'], translation: 'Машину недавно отремонтировали.' },
      { sentence: 'The window ___ by the children.',     hint: 'break — Past Passive',          answers: ['was broken'],        translation: 'Окно было разбито детьми.' },
    ],
  },
];
